version: '3.7'
# version du docker-compose qu'on souhaite utiliser

services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx
    networks:
      - inception_volume
    env_file:
      - ./.env
    build:
      context: ./requirements/nginx/
    volumes:
      - wordpress:/var/www/wordpress/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always
  wordpress:
    container_name: wordpress
    hostname: wordpress
    image: wordpress
    networks:
      - inception_volume
    env_file:
      - ./.env
    build:
      context: ./requirements/wordpress/
    volumes:
      - wordpress:/var/www/wordpress/
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb
    networks:
      - inception_volume
    env_file:
      - ./.env
    build:
      context: ./requirements/mariadb/
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped

volumes:
  wordpress:
    driver: "local"
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ldermign/data/wordpress'
  mariadb:
    driver: "local"
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ldermign/data/mariadb'

networks:
  inception_volume:
    driver: bridge





# arguments...
# services:
# definition d'un conteneur
# build:
# chercher le Dokerfile qui va construire l'image qui va faire tourner le container
# networks:
# a quel reseau le container doit appartenir
# image:
# description du conteneur : c'est une image docker ici
# or, on veut creer a partir d'un docker file, donc on va utiliser build
# container_name:
# le nom du container
# restart:
# fonction qui specifie ce que doit faire le container s'il crash
# volumes:
# fichier sur le disque qui va etre monte sur un fichier du container.
# C'est similaire a un dossier partage.  
# syntaxe -> {PATH_TO_DISK_FOLDER}:{PATH_TO_CONTAINER_FOLDER}:PERMISSIONS (:ro, :rw...) (pas obligatoire)
# depends_on:
# assure qu'un container est construit avant un autre
# utile pour wordpress qui a besoin d'une database (mariadb) pour fonctionner